# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "http://combatlan.com/" # the base hostname & protocol for your site
title: CombatLAN / 
permalink: /news/:title
comments: disqus
email: admin@combatlan.com
description: CombatLAN is southeast Ohios premier PC Gaming / LAN party community
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#UPDATE GOOGLE ANALYTICS!!!!!!
analytics :
  provider : google
  google : 
      tracking_id : 'UA-73152722-1'
# Build settings
markdown: kramdown
port: 8080
timezone: America/Detroit
encoding: utf-8